### PR TITLE
Update PitDeductInAdvanceForm1.js

### PR DESCRIPTION
**Pull request by adam429**
Update a error number in PITDeductInAdvanceForm.

should be "16920" instead of "16829"

### CODE REVIEW

**Comment by adam429** [comment]
Update a error number in PITDeductInAdvanceForm.

should be "16920" instead of "16829"

**Review by wxqee — COMMENTED** [review]
Has a reference link or document please?

**Comment by adam429** [comment]
Yes, there are lots of Deduct Advance table. 

Check these links below:

https://zhuanlan.zhihu.com/p/43496375
https://www.gerensuodeshui.cn/

**Review by wxqee — APPROVED** [review]

**Comment by wxqee** [comment]
> Yes, there are lots of Deduct Advance table.
> 
> Check these links below:
> 
> https://zhuanlan.zhihu.com/p/43496375
> https://www.gerensuodeshui.cn/

thank you ^_^

pr merged.

**Pull request merged**
